"""Initial migration

Revision ID: 0add9ab66405
Revises: 
Create Date: 2026-01-31 17:59:42.710421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0add9ab66405'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('bet_slips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slip_type', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bet_slips_id'), 'bet_slips', ['id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bet_slip_id', sa.Integer(), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('recommended_bets', sa.JSON(), nullable=True),
    sa.Column('parlay_suggestions', sa.JSON(), nullable=True),
    sa.Column('risk_assessment', sa.String(), nullable=True),
    sa.Column('prop_analyses', sa.JSON(), nullable=True),
    sa.Column('analysis_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bet_slip_id'], ['bet_slips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bet_slip_id')
    )
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_table('prop_bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bet_slip_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('opponent_name', sa.String(), nullable=True),
    sa.Column('stat_type', sa.String(), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('over_under', sa.String(), nullable=False),
    sa.Column('game_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('odds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bet_slip_id'], ['bet_slips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prop_bets_id'), 'prop_bets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prop_bets_id'), table_name='prop_bets')
    op.drop_table('prop_bets')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_bet_slips_id'), table_name='bet_slips')
    op.drop_table('bet_slips')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
